- name: Validate user-defined conditions
  ansible.builtin.assert:
    that:
      - >
        (item.operator == "equals" and vars.get(item.var_name, omit) == item.value) or
        (item.operator == "not_equals" and vars.get(item.var_name, omit) != item.value) or
        (item.operator == "greater_than" and (vars.get(item.var_name, omit) | default(0) | int) > (item.value | int)) or
        (item.operator == "less_than" and (vars.get(item.var_name, omit) | default(0) | int) < (item.value | int)) or
        (item.operator == "contains" and item.value in (vars.get(item.var_name, omit) | default("") | string))
    msg: "Condition failed: {{ item.var_name }} {{ item.operator }} {{ item.value }}"
  loop: "{{ decision_node_conditions }}"

- name: Set fact for workflow decision
  ansible.builtin.set_fact:
    conditions_met: true
